CREATE TABLE AUD_DOCENTES(
ID NUMERIC NOT NULL,
ACCION VARCHAR2(40),
FECHA DATE,
USUARIO VARCHAR2(30)
);

CREATE TABLE DOCENTES (
DOCUMENTO NUMERIC NOT NULL,
NOMBRE VARCHAR2(40),
MATERIA VARCHAR2(30)
);

INSERT INTO DOCENTES (DOCUMENTO, NOMBRE, MATERIA) VALUES (1, 'Tyna','NEGOCIACION');
INSERT INTO DOCENTES (DOCUMENTO, NOMBRE, MATERIA) VALUES (2, 'Cintia', 'PHYTON');
INSERT INTO DOCENTES (DOCUMENTO, NOMBRE, MATERIA) VALUES (3, 'Valery', '');
INSERT INTO DOCENTES (DOCUMENTO, NOMBRE, MATERIA) VALUES (4, 'Elsa', 'PHYTON');
INSERT INTO DOCENTES (DOCUMENTO, NOMBRE, MATERIA) VALUES (5, 'Marleny', 'JAVA');
INSERT INTO DOCENTES (DOCUMENTO, NOMBRE, MATERIA) VALUES (6, 'Clara', 'ALGEBRA');
INSERT INTO DOCENTES (DOCUMENTO, NOMBRE, MATERIA) VALUES (7, 'Yoshi', 'ALGEBRA');
INSERT INTO DOCENTES (DOCUMENTO, NOMBRE, MATERIA) VALUES (8, 'Mercedes','ALGEBRA');
INSERT INTO DOCENTES (DOCUMENTO, NOMBRE, MATERIA) VALUES (9, 'Gabriel','ALGEBRA');
INSERT INTO DOCENTES (DOCUMENTO, NOMBRE, MATERIA) VALUES (10, 'Eugenio', 'BD');
INSERT INTO DOCENTES (DOCUMENTO, NOMBRE, MATERIA) VALUES (11, 'Dario', '');
INSERT INTO DOCENTES (DOCUMENTO, NOMBRE, MATERIA) VALUES (12, 'Maryori','PHYTON');
INSERT INTO DOCENTES (DOCUMENTO, NOMBRE, MATERIA) VALUES (13, 'Rosalba', 'BD');
INSERT INTO DOCENTES (DOCUMENTO, NOMBRE, MATERIA) VALUES (14, 'Ruben','PHYTON');
INSERT INTO DOCENTES (DOCUMENTO, NOMBRE, MATERIA) VALUES (15, 'Blanca', 'JAVA');
INSERT INTO DOCENTES (DOCUMENTO,NOMBRE,MATERIA) VALUES( 16,'ALAM BRITO', 'NEGOCIACION DE TECNOLOGIA');

SELECT * FROM DOCENTES;
SELECT * FROM AUD_DOCENTES;


CREATE OR REPLACE TRIGGER SEGUIMIENTO_DOCENTES
AFTER INSERT ON DOCENTES
FOR EACH ROW
DECLARE
V_USERNAME varchar2(40);
V_FECHA date;
BEGIN
SELECT USER INTO V_USERNAME FROM DUAL;
SELECT SYSDATE INTO V_FECHA FROM DUAL;
INSERT INTO aud_docentes (ID,ACCION, FECHA, USUARIO)VALUES ('I-'||:NEW.DOCUMENTO,'SE HA AGREGADO UN NUEVO DOCENTE'
||:NEW.NOMBRE,V_FECHA,V_USERNAME);
END;

CREATE OR REPLACE TRIGGER SEGUIMIENTO_DOCENTES
AFTER INSERT ON DOCENTES
FOR EACH ROW
DECLARE
V_USERNAME VARCHAR2(40);
V_FECHA DATE;
BEGIN
    SELECT USER INTO V_USERNAME FROM DUAL;
    SELECT SYSDATE INTO V_FECHA FROM DUAL;
    INSERT INTO AUD_DOCENTES (DOCUMENTO,ACCION, FECHA, USUARIO) VALUES (:NEW.DOCUMENTO,'SE AGREGO UN NUEVO DOCENTE '
    ||:NEW.NOMBRE,V_FECHA,V_USERNAME);
END;

INSERT INTO DOCENTES (DOCUMENTO, NOMBRE, MATERIA) VALUES( 9999,'ALAM BRITO', 'NEGOCIACION DE TECNOLOGIA');

DROP TRIGGER BORRAR_DOCENTES;
CREATE OR REPLACE TRIGGER BORRAR_DOCENTES
BEFORE DELETE ON DOCENTES
FOR EACH ROW
DECLARE
V_USERNAME VARCHAR2(40);
V_FECHA DATE;
BEGIN
    SELECT user INTO V_USERNAME FROM DUAL;
    SELECT SYSDATE INTO V_FECHA from DUAL;
    INSERT INTO AUD_DOCENTES (DOCUMENTO,ACCION, FECHA, USUARIO) VALUES (:OLD.DOCUMENTO,'SE BORRO UN DOCENTE '
    ||:OLD.NOMBRE,V_FECHA,V_USERNAME);
END;


DROP TRIGGER UPDATE_DOCENTES;
CREATE OR REPLACE TRIGGER UPDATE_DOCENTES
AFTER UPDATE OF DOCUMENTO, NOMBRE, MATERIA ON DOCENTES
FOR EACH ROW
DECLARE
V_USERNAME VARCHAR2(40);
V_FECHA DATE;
BEGIN
    SELECT user INTO V_USERNAME FROM DUAL;
    SELECT SYSDATE INTO V_FECHA from DUAL;
    INSERT INTO AUD_DOCENTES (DOCUMENTO,ACCION, FECHA, USUARIO) VALUES (:OLD.DOCUMENTO,'SE ACTUALIZO EL DOCENTE '
    ||:NEW.NOMBRE,V_FECHA,V_USERNAME);
END;

UPDATE DOCENTES SET NOMBRE = 'ALAN' WHERE DOCUMENTO = 3;










CREATE OR REPLACE TRIGGER ACTUALIZACION_DOCENTES 
AFTER UPDATE OF MATERIA,NOMBRE,DOCUMENTO ON DOCENTES 
FOR EACH ROW
DECLARE
V_USERNAME VARCHAR2(40);
V_FECHA DATE;
BEGIN
  SELECT user INTO V_USERNAME FROM DUAL;
    SELECT SYSDATE INTO V_FECHA from DUAL;
    INSERT INTO AUD_DOCENTES (DOCUMENTO,ACCION, FECHA, USUARIO) VALUES (:OLD.DOCUMENTO,'SE ACTUALIZO EL DOCENTE '
    ||:NEW.NOMBRE,V_FECHA,V_USERNAME);
END;
















